package ru.mos.efp.efp.drools.rpr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlApplicationOk implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public XmlApplicationOk() {
    }

}