package ru.mos.efp.efp.drools.rpr;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class XmlStatus implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    private String xml;

    public XmlStatus() {
    }
    
    public XmlStatus(String xml) {
        this.xml = xml;
    }
    
    public String getXml() {
        return this.xml;
    }
    
    public void setXml(String xml) {
        this.xml = xml;
    }

}